# This workflow will build a Java project with Maven 
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      id: build
      run: |
          mvn -B clean package
          mkdir -p ~/artifacts
          cp "2006Scape Client/target/client-1.0-jar-with-dependencies.jar" ~/artifacts/Client.jar
          cp "2006Scape Server/target/server-1.0-jar-with-dependencies.jar" ~/artifacts/Server.jar
          cp "2006Scape Server/ServerConfig.Sample.json" ~/artifacts/ServerConfig.json
          cp SinglePlayer.bat ~/artifacts/
          cp -r "2006Scape Server/plugins" ~/artifacts/
          cp -r "2006Scape Server/data" ~/artifacts/
    - name: Publish build to GH Actions
      uses: actions/upload-artifact@v3
      with:
          path: ~/artifacts/*
          name: 2006Scape-SinglePlayer
